# Generated by Django 5.0.6 on 2024-06-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, upload_to='images')),
                ('bio', models.TextField()),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=255)),
            ],
            options={
                'db_table': 'employee_table',
            },
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
            options={
                'db_table': 'payment_table',
            },
        ),
        migrations.CreateModel(
            name='SubmissionModel',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateField()),
                ('status', models.CharField(default='pending', max_length=255)),
            ],
            options={
                'db_table': 'submission_table',
            },
        ),
        migrations.CreateModel(
            name='EmployeeReviewModel',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=500)),
                ('rating', models.IntegerField(default=1)),
                ('status', models.CharField(default='active', max_length=255)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employeemodel')),
            ],
            options={
                'db_table': 'employee_review_table',
            },
        ),
    ]
