# Generated by Django 5.0.6 on 2024-06-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployeeApp', '0001_initial'),
        ('HirerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereviewmodel',
            name='hirer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HirerApp.hirermodel'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employeemodel'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HirerApp.jobmodel'),
        ),
        migrations.AddField(
            model_name='submissionmodel',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employeemodel'),
        ),
        migrations.AddField(
            model_name='submissionmodel',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HirerApp.jobmodel'),
        ),
    ]
